{{- if .Values.enableExtraModels }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-style-gpu-unaccelerated
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.styleHttpPort}}
    protocol: TCP
    targetPort: {{ .Values.styleHttpPort}}
  - name: grpc
    port: {{ .Values.styleGrpcPort}}
    protocol: TCP
    targetPort: {{ .Values.styleGrpcPort}}
  - name:  metrics
    port: {{ .Values.stylePromPort}}
    protocol: TCP
    targetPort: {{ .Values.stylePromPort}}
  selector:
    app: {{ .Release.Name }}-style-gpu-unaccelerated
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-style-cpu-unaccelerated
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.styleHttpPort}}
    protocol: TCP
    targetPort: {{ .Values.styleHttpPort}}
  - name: grpc
    port: {{ .Values.styleGrpcPort}}
    protocol: TCP
    targetPort: {{ .Values.styleGrpcPort}}
  - name:  metrics
    port: {{ .Values.stylePromPort}}
    protocol: TCP
    targetPort: {{ .Values.stylePromPort}}
  selector:
    app: {{ .Release.Name }}-style-cpu-unaccelerated
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-style-cpu-accelerated
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.styleHttpPort}}
    protocol: TCP
    targetPort: {{ .Values.styleHttpPort}}
  - name: grpc
    port: {{ .Values.styleGrpcPort}}
    protocol: TCP
    targetPort: {{ .Values.styleGrpcPort}}
  - name:  metrics
    port: {{ .Values.stylePromPort}}
    protocol: TCP
    targetPort: {{ .Values.stylePromPort}}
  selector:
    app: {{ .Release.Name }}-style-cpu-accelerated
{{- end }}
