{{- if and .Values.prometheus.enabled .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-gpt2
  namespace: monitoring
  labels:
    app: {{ .Release.Name }}-gpt2
    prometheus: {{ .Values.prometheus.serviceMonitor.prometheusInstance }}
    {{- with .Values.prometheus.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ .Release.Name }}-gpt2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-gpt2
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - targetPort: {{ .Values.gpt2PromPort }}
    path: "/metrics"
    interval: "60s"
    scrapeTimeout: "30s"
    honorLabels: {{ .Values.prometheus.serviceMonitor.honorLabels }}
{{- end }}

