---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.chatPort }}
  selector:
    app: {{ .Release.Name }}-chat
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-taiapi
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.taiapiPort }}
    protocol: TCP
    targetPort: {{ .Values.taiapiPort }}
  selector:
    app: {{ .Release.Name }}-taiapi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gpt2
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.gpt2HttpPort}}
    protocol: TCP
    targetPort: {{ .Values.gpt2HttpPort}}
  - name: grpc
    port: {{ .Values.gpt2GrpcPort}}
    protocol: TCP
    targetPort: {{ .Values.gpt2GrpcPort}}
  - name:  metrics
    port: {{ .Values.gpt2PromPort}}
    protocol: TCP
    targetPort: {{ .Values.gpt2PromPort}}
  selector:
    app: {{ .Release.Name }}-gpt2
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-style
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.styleHttpPort}}
    protocol: TCP
    targetPort: {{ .Values.styleHttpPort}}
  - name: grpc
    port: {{ .Values.styleGrpcPort}}
    protocol: TCP
    targetPort: {{ .Values.styleGrpcPort}}
  - name:  metrics
    port: {{ .Values.stylePromPort}}
    protocol: TCP
    targetPort: {{ .Values.stylePromPort}}
  selector:
    app: {{ .Release.Name }}-style

{{- if .Values.enableExtraModels }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-style-gpu-accelerated
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.styleHttpPort}}
    protocol: TCP
    targetPort: {{ .Values.styleHttpPort}}
  - name: grpc
    port: {{ .Values.styleGrpcPort}}
    protocol: TCP
    targetPort: {{ .Values.styleGrpcPort}}
  - name:  metrics
    port: {{ .Values.stylePromPort}}
    protocol: TCP
    targetPort: {{ .Values.stylePromPort}}
  selector:
    app: {{ .Release.Name }}-style
{{- end }}
