---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.frontendPort }}
  selector:
    app: {{ .Release.Name }}-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.apiPort }}
    protocol: TCP
    targetPort: {{ .Values.apiPort }}
  selector:
    app: {{ .Release.Name }}-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-style
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.styleHttpPort}}
    protocol: TCP
    targetPort: {{ .Values.styleHttpPort}}
  - name: grpc
    port: {{ .Values.styleGrpcPort}}
    protocol: TCP
    targetPort: {{ .Values.styleGrpcPort}}
  - name:  metrics
    port: {{ .Values.stylePromPort}}
    protocol: TCP
    targetPort: {{ .Values.stylePromPort}}
  selector:
    app: {{ .Release.Name }}-style

{{- if .Values.enableExtraModels }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-style-gpu-accelerated
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.styleHttpPort}}
    protocol: TCP
    targetPort: {{ .Values.styleHttpPort}}
  - name: grpc
    port: {{ .Values.styleGrpcPort}}
    protocol: TCP
    targetPort: {{ .Values.styleGrpcPort}}
  - name:  metrics
    port: {{ .Values.stylePromPort}}
    protocol: TCP
    targetPort: {{ .Values.stylePromPort}}
  selector:
    app: {{ .Release.Name }}-style
{{- end }}
