version: "3.9"
services:
  imagefrontend: #YOUR APP
    image: transparent-ai/imagefrontend
    environment:
      API_HOST: api
      API_PORT: 8050
      PYTHONUNBUFFERED: 1
    ports:
      - "8888:8888"
  api: # PRE and POST PROCESSING
    image: transparent-ai/api
    environment:
      CONFIG_FILE: "/config/config.yaml"
      #      TARGET_ENDPOINT: "style:8000"
      # There are a few names that we've used over the course of development
      #MODEL_NAME: "magenta_arbitrary-image-stylization-v1"
      #TARGET_NAME: "magenta_image_stylization"
      #default:
      #TARGET_ENDPOINT: "style:8000"
      #TARGET_MODEL: "magenta_image_stylization"
      #cpu_normal:
      #TARGET_ENDPOINT_CPU_NORMAL: "style:8000"
      #TARGET_NAME_CPU_NORMAL: "magenta_image_stylization"
      #cpu_optimized:
      #TARGET_ENDPOINT_CPU_OPTIMIZED: "style:8000"
      #TARGET_MODEL_CPU_OPTIMIZED: "magenta_image_stylization"
      #gpu_normal:
      #TARGET_ENDPOINT_GPU_NORMAL: "style:8000"
      #TARGET_MODEL_GPU_NORMAL: "magenta_image_stylization"
      #gpu_optimized: 
      #TARGET_ENDPOINT_GPU_OPTIMIZED: "style:8000"
      #TARGET_MODEL_GPU_OPTIMIZED: "magenta_image_stylization"
    volumes:
      - type: bind
        source: local_config
        target: /config
    ports:
      - "8050:8050"
  style: # MODEL containzerized by octoml in triton inference server
    image: transparent-ai/style
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    command: tritonserver --model-repository=octoml/models --strict-model-config=false
