ersion: "3.9"
services:
  frontend: # YOUR APP
    image: transparent-ai/frontend
    environment:
      API_HOST: api
      API_PORT: 8050
    ports:
      - "8888:8888"
  api: # PRE and POST PROCESSING
    image: transparent-ai/api
    environment:
      MODEL_ENDPOINT: "style:8000"
      # There are a few names that we've used over the course of development
      MODEL_NAME: "magenta_image_stylization"
    ports:
      - "8050:8050"
  style: # MODEL containzerized by octoml in triton inference server
    image: transparent-ai/style
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    command: tritonserver --model-repository=octoml/models --strict-model-config=false