version: "3.9"
services:
  taiapi:
    image: transparent-ai/tai-api
    environment:
      OCTO_HOST: gpt2
    ports:
      - "9000:9000"
  gpt2:
    image: transparent-ai/gpt2-lm-head-10
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    command: tritonserver --model-repository=octoml/models --strict-model-config=false
  chat:
    image: transparent-ai/chat
    environment:
      TAI_API_HOST: taiapi
    ports:
      - "3000:3000"
