version: "3.9"
services:
  imagefrontend: #YOUR APP
    image: transparent-ai/imagefrontend
    environment:
      TAI_API_HOST: taiapi
      API_HOST: api
      API_PORT: 8050
      PYTHONUNBUFFERED: 1
      #STYLE_IMAGE: "tensor_dog_crop_crop.jpg"
      STYLE_IMAGE: "tensor_dog.jpg"
    ports:
      - "8888:8888"
  api: # PRE and POST PROCESSING
    image: transparent-ai/api
    environment:
      MODEL_ENDPOINT: "style:8000"
      # There are a few names that we've used over the course of development
      #MODEL_NAME: "magenta_arbitrary-image-stylization-v1"
      MODEL_NAME: "magenta_image_stylization"
    ports:
      - "8050:8050"
  style: # MODEL containzerized by octoml in triton inference server
    image: transparent-ai/style
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    command: tritonserver --model-repository=octoml/models --strict-model-config=false
