{
 "title": "Triton Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Triton Servers online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(nv_inference_count) by (container)) "
    }
   ]
  },
  {
   "title": "Number of GPUs online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(nv_gpu_utilization) by (gpu_uuid)) "
    }
   ]
  },
  { "title": "Inference Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total Inferences per model",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (model) (nv_inference_count)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Inference Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(nv_inference_compute_infer_duration_us[1m])",
     "legendFormat": "{{ model }} on {{ container }}"
    }
   ]
  },
  {
   "title": "Inference Request Success by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nv_inference_request_success[1m])) by (container)",
     "legendFormat": "{{  container }}"
    }
   ]
  },
  {
   "title": "Inference Request Failures by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nv_inference_request_failure[1m])) by (container)",
     "legendFormat": "{{  container }}"
    }
   ]
  },
  {
   "title": "Average Queue Time by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rate(nv_inference_queue_duration_us[1m])/(1+rate(nv_inference_request_success[1m]))) by (container)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Proportion of Requests by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (container) (rate(nv_inference_count[1m])) / ignoring(container) group_left sum (rate(nv_inference_count[1m]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "GPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nv_gpu_utilization",
     "legendFormat": "{{ gpu_uuid }} on {{ instance }}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes / nv_gpu_memory_total_bytes",
     "legendFormat": "{{ gpu_uuid }} on {{ instance }}"
    }
   ]
  }
 ]
}