# Number of replicas for the Deployment
replicas:
  frontend: 1
  api: 1
  style: 1

# Ports
frontendPort: 8888
apiPort: 8050
styleHttpPort: 8000
styleGrpcPort: 8001
stylePromPort: 8002

# Full path (url) to the image and the tag to use
imageRegistry: gcr.io/octonaut-skrum
images:
  frontend:
    name: frontend
    tag: latest
  api:
    name: api
    tag: latest
  style:
    # this is optimzied, this is not what's made by `just docker-build` 
    # this is made by the octoml platform and is 20% faster than tensorflow and 70% fastert han onnx on a t4gpu (g4dn.xlarge)  
    name: fullaccel-magenta_image_stylization-aws_g4dn.xlarge 
    tag: latest

ingress:
  enabled: false
  host: example.com
  annotations: {}
  ingressClassName: alb
  path: /
  pathType: Prefix
  tls: []

tolerations: []
## If you want to set tolerations, delete the `[]` in the line above
## and uncomment/fill in this example block
# - key: "octoml.ai/octomizer-platform"
#   operator: "Equal"
#   value: "aws-c6g.large"
#   effect: "NoSchedule"

models:
  style:
    nodeSelector:
      node.kubernetes.io/instance-type: "g4dn.2xlarge"

## If you want to set node selector, delete the `{}` in the line above
## and uncomment/fill in this example block
#  octoml.ai/octomizer-platform: "aws-c6g.large"
#  label-key: "label-value"

prometheus:
  enabled: true
  metricsPort: 8002
  serviceMonitor:
    enabled: false
    prometheusInstance: default
    labels: {}
    honorLabels: false

# Extra models here are provided to graphically show speed comparisons
# If you don't trust our web ui
# we defaul to accelerated on gpu(g4dn.xlarge), so also show unaccelerated on gpu, accelerated on cpu(c5n.xlarge), and unaccelerated on cpu
# Graviton(m6g.xlarge) got really poor perf so not including it today (2x slower than skylake(c5n.xlarge))
enableExtraModels: true
# documentation only:
#extraModels:
#  - style-gpu-unaccelerated
#  - style-cpu-unaccelerated
#  - style-cpu-accelerated
