---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tai-cannon
  name: tai-cannon
  namespace: transparentai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tai-cannon
  template:
    metadata:
      labels:
        app: tai-cannon
    spec:
      imagePullSecrets:
      - name: pull-secret
      containers:
      - name: tai-cannon-1
        imagePullPolicy: Always
        image: gcr.io/octonaut-skrum/api
        command: ["python"]
        args: ["test.py"]
        env:
        - name: LOOP
          value: "1"
        - name: MODEL_ENDPOINT
          value: "transparentai-style-cpu-accelerated:8000"
        - name: MODEL_NAME
          value: "magenta_image_stylization"
      - name: tai-cannon-2
        imagePullPolicy: Always
        image: gcr.io/octonaut-skrum/api
        command: ["python"]
        args: ["test.py"]
        env:
        - name: LOOP
          value: "1"
        - name: MODEL_ENDPOINT
          value: "transparentai-style-cpu-unaccelerated:8000"
        - name: MODEL_NAME
          value: "magenta_arbitrary-image-stylization-v1"
      - name: tai-cannon-3
        imagePullPolicy: Always
        image: gcr.io/octonaut-skrum/api
        command: ["python"]
        args: ["test.py"]
        env:
        - name: LOOP
          value: "1"
        - name: MODEL_ENDPOINT
          value: "transparentai-style-gpu-accelerated:8000"
        - name: MODEL_NAME
          value: "magenta_image_stylization"
