targets:
  # TODO: add in proc options
  # cpu_in_proc:
  # gpu_in_proc:
  default:
    endpoint: !env TARGET_ENDPOINT http://host.docker.internal:8000
    model: !env TARGET_MODEL magenta_image_stylization
  cpu:
    endpoint: !env TARGET_ENDPOINT_CPU_NORMAL http://host.docker.internal:8000
    model: !env TARGET_NAME_CPU_NORMAL magenta_image_stylization  
  cpu_accelerated:
    endpoint: !env TARGET_ENDPOINT_CPU_OPTIMIZED http://host.docker.internal:8000
    model: !env TARGET_MODEL_CPU_OPTIMIZED magenta_image_stylization  
  gpu:
    endpoint: !env TARGET_ENDPOINT_GPU_NORMAL http://host.docker.internal:8000
    model: !env TARGET_MODEL_GPU_NORMAL magenta_image_stylization  
  gpu_accelerated: 
    endpoint: !env TARGET_ENDPOINT_GPU_OPTIMIZED http://host.docker.internal:8000    
    model: !env TARGET_MODEL_GPU_OPTIMIZED magenta_image_stylization
