name: PR Tests

on:
  pull_request:
    branches: [main]

env:
  OCTOML_EMPLOYEE: 1
  OCTOML_AGREE_TO_TERMS: 1
  OCTOML_TELEMETRY: false

jobs:
  runtest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: setup just
        uses: extractions/setup-just@v1
      - name: Make parent dirs for octoml-bin
        run: mkdir -p target/debug
      - name: Download octoml-bin (tar.gz)
        run: curl --fail ${{secrets.CLI_DOWNLOAD_LINK_UBUNTU}} --output octoml.tar.gz && tar xzf octoml.tar.gz && mv octoml target/debug/octoml
      - name: Show Download
        run: ls -lR target/debug/octoml
      - name: chmod octoml bin
        run: chmod 775 target/debug/octoml
      - name: copy bin to /usr/bin
        run: sudo cp target/debug/octoml /usr/bin/
      - name: print octoml version
        run: octoml -V
      - name: run docker build
        run: just docker-build
      - name: docker compose up
        run: docker-compose up -d
      - name: sleep 100 # taiapi pulls a big file from the internet
        run: sleep 100
      - name: docker ps
        run: docker ps
      - name: check chat
        run: curl localhost:3000
      - name: check inferenceserver
        run: curl localhost:8000/v2/health/ready
      - name: check taiapi
        run: curl localhost:9000
      - name: validate that helm chart can be packaged, this doesn't push it but does some sanity checking on the helm chart
        run: cd deploy/helm && helm package .
