name: PR Tests

on:
  pull_request:
    branches: [main]

env:
  OCTOML_EMPLOYEE: 1
  OCTOML_AGREE_TO_TERMS: 1
  OCTOML_TELEMETRY: false

jobs:
  runtest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Setup Just - Command Runner
        uses: extractions/setup-just@v1
      - name: OctoML CLI - Prepare target path
        run: mkdir -p target/debug
      - name: OctoML CLI - Download
        run: curl --fail ${{secrets.CLI_DOWNLOAD_LINK_UBUNTU}} --output octoml.tar.gz && tar xzf octoml.tar.gz && mv octoml target/debug/octoml
      - name: OctoML CLI - Verify
        run: ls -lR target/debug/octoml
      - name: OctoML CLI - Set Executable
        run: chmod 775 target/debug/octoml
      - name: OctoML CLI - Copy to Path
        run: sudo cp target/debug/octoml /usr/bin/
      - name: OctoML CLI - Print version
        run: octoml -V
      - name: Build Model Container
        run: just build-model
      - name: Docker - Compose Up
        run: docker-compose up -d
      - name: Sleep 30
        run: sleep 30
      - name: Docker - Status
        run: docker ps -a
      - name: Check Model server
        run: curl localhost:8000/v2/health/ready        
      - name: Check Api
        run: curl localhost:8050
      - name: Check Frontend
        run: curl localhost:8888        
      - name: Validate that helm chart can be packaged, this doesn't push it but does some sanity checking on the helm chart
        run: cd deploy/helm && helm package .
